import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import readline from 'readline';
import { spawn } from 'child_process';

const ENV_LOCAL_PATH = path.join(process.cwd(), '.env.local');
const ENV_PATH = path.join(process.cwd(), '.env');
const STATE_FILE_PATH = path.join(process.cwd(), 'data', 'bangkok-tracker-state.json');
const INITIAL_STATE_PATH = path.join(process.cwd(), 'data', 'initial-state.json');

// ANSI color helpers
const c = {
  reset: '\x1b[0m',
  bold: '\x1b[1m',
  dim: '\x1b[2m',
  emerald: '\x1b[38;2;34;197;94m',
  cyan: '\x1b[38;2;6;182;212m',
  blue: '\x1b[38;2;59;130;246m',
  yellow: '\x1b[38;2;245;158;11m',
  rose: '\x1b[38;2;244;63;94m',
  white: '\x1b[37m',
  slate: '\x1b[38;2;148;163;184m',
};

function parseEnvFile(filePath: string): Record<string, string> {
  const result: Record<string, string> = {};
  if (!fs.existsSync(filePath)) return result;

  const content = fs.readFileSync(filePath, 'utf-8');
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx > 0) {
      const key = trimmed.slice(0, eqIdx).trim();
      let val = trimmed.slice(eqIdx + 1).trim();
      if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
        val = val.slice(1, -1);
      }
      result[key] = val;
    }
  }
  return result;
}

function runCommand(command: string, args: string[], env: NodeJS.ProcessEnv = process.env): Promise<void> {
  return new Promise((resolve, reject) => {
    const isWindows = process.platform === 'win32';
    const child = spawn(isWindows && !command.endsWith('.cmd') && !command.endsWith('.exe') ? `${command}.cmd` : command, args, {
      stdio: 'inherit',
      shell: isWindows,
      env: { ...process.env, ...env },
    });

    child.on('error', (err) => reject(err));
    child.on('close', (code) => {
      if (code === 0) {
        resolve();
      } else {
        reject(new Error(`Command '${command} ${args.join(' ')}' exited with code ${code}`));
      }
    });
  });
}

function promptQuestion(rl: readline.Interface, query: string): Promise<string> {
  return new Promise((resolve) => {
    rl.question(query, (ans) => resolve(ans.trim()));
  });
}

async function main() {
  console.clear();
  console.log(`
${c.emerald}${c.bold}========================================================================${c.reset}
${c.emerald}${c.bold}   🏛️  Bangkok 50 Districts Tracker — Interactive First-Time Setup       ${c.reset}
${c.emerald}${c.bold}========================================================================${c.reset}
${c.slate}This setup script will configure your environment, build the project,
and initialize the database/storage ready for development or production.${c.reset}
`);

  // 1. Read existing configs from .env.local or .env if available
  const existingEnv = { ...parseEnvFile(ENV_PATH), ...parseEnvFile(ENV_LOCAL_PATH) };

  const defaultDbUrl = existingEnv.DATABASE_URL || existingEnv.POSTGRES_URL || '';
  const defaultAdminPassword = existingEnv.ADMIN_PASSWORD || 'bkk2026';
  const autoGeneratedJwt = crypto.randomBytes(32).toString('hex');
  const defaultJwtSecret = existingEnv.JWT_SECRET || autoGeneratedJwt;

  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  console.log(`${c.cyan}${c.bold}--- [1/4] Environment Configuration ---${c.reset}\n`);

  // Prompt DATABASE_URL
  console.log(`${c.bold}1. PostgreSQL Database Connection URL (Neon / Vercel Postgres)${c.reset}`);
  console.log(`${c.slate}   (Optional: Press Enter to skip and use offline local JSON file storage)${c.reset}`);
  const dbPrompt = defaultDbUrl
    ? `${c.slate}   Default: [${defaultDbUrl}]${c.reset}\n   ${c.emerald}DATABASE_URL:${c.reset} `
    : `   ${c.emerald}DATABASE_URL:${c.reset} `;
  const inputDbUrl = await promptQuestion(rl, dbPrompt);
  const finalDbUrl = inputDbUrl || defaultDbUrl;

  console.log();

  // Prompt ADMIN_PASSWORD
  console.log(`${c.bold}2. Admin Dashboard Password${c.reset}`);
  console.log(`${c.slate}   Used to access /admin place manager, toggles, and state backups.${c.reset}`);
  const passPrompt = `${c.slate}   Default: [${defaultAdminPassword}]${c.reset}\n   ${c.emerald}ADMIN_PASSWORD:${c.reset} `;
  const inputAdminPassword = await promptQuestion(rl, passPrompt);
  const finalAdminPassword = inputAdminPassword || defaultAdminPassword;

  console.log();

  // Prompt JWT_SECRET
  console.log(`${c.bold}3. JWT Secret Key (HMAC-SHA256 Session Signature)${c.reset}`);
  console.log(`${c.slate}   Auto-generated 64-character cryptographic hex string.${c.reset}`);
  const jwtPrompt = `${c.slate}   Default: [${defaultJwtSecret}]${c.reset}\n   ${c.emerald}JWT_SECRET:${c.reset} `;
  const inputJwtSecret = await promptQuestion(rl, jwtPrompt);
  const finalJwtSecret = inputJwtSecret || defaultJwtSecret;

  rl.close();

  console.log(`\n${c.cyan}${c.bold}--- [2/4] Saving Configuration ---${c.reset}`);

  // Build .env.local content
  const envLines = [
    '# ----------------------------------------------------',
    '# Bangkok 50 Districts Tracker - Local Environment',
    `# Generated at: ${new Date().toISOString()}`,
    '# ----------------------------------------------------',
    '',
    '# Database Connection (Neon / Vercel Postgres)',
    `DATABASE_URL="${finalDbUrl}"`,
    `POSTGRES_URL="${finalDbUrl}"`,
    '',
    '# Admin Authentication',
    `ADMIN_PASSWORD="${finalAdminPassword}"`,
    `JWT_SECRET="${finalJwtSecret}"`,
    '',
  ];

  fs.writeFileSync(ENV_LOCAL_PATH, envLines.join('\n'), 'utf-8');
  console.log(`${c.emerald}✓ Configuration written to .env.local${c.reset}`);

  // Update process.env for subsequent child processes
  process.env.DATABASE_URL = finalDbUrl;
  process.env.POSTGRES_URL = finalDbUrl;
  process.env.ADMIN_PASSWORD = finalAdminPassword;
  process.env.JWT_SECRET = finalJwtSecret;

  // 2. Run Project Build
  console.log(`\n${c.cyan}${c.bold}--- [3/4] Building Next.js 14 Application ---${c.reset}`);
  console.log(`${c.slate}Executing: bun run build...${c.reset}\n`);

  try {
    await runCommand('bun', ['run', 'build'], {
      DATABASE_URL: finalDbUrl,
      POSTGRES_URL: finalDbUrl,
      ADMIN_PASSWORD: finalAdminPassword,
      JWT_SECRET: finalJwtSecret,
    });
    console.log(`\n${c.emerald}✓ Build completed successfully.${c.reset}`);
  } catch (err: any) {
    console.warn(`\n${c.yellow}⚠️ Next.js build encountered a warning: ${err.message}${c.reset}`);
    console.log(`${c.slate}Continuing with database initialization...${c.reset}`);
  }

  // 3. Database Initialization & Seeding
  console.log(`\n${c.cyan}${c.bold}--- [4/4] Database & Storage Initialization ---${c.reset}`);

  if (finalDbUrl && finalDbUrl.trim().length > 0) {
    console.log(`${c.blue}Detected PostgreSQL connection. Pushing schema with Drizzle Kit...${c.reset}`);
    try {
      await runCommand('bun', ['run', 'db:push'], {
        DATABASE_URL: finalDbUrl,
        POSTGRES_URL: finalDbUrl,
      });
      console.log(`${c.emerald}✓ Schema pushed to PostgreSQL database.${c.reset}`);

      console.log(`\n${c.blue}Seeding initial Bangkok 50 districts starter data...${c.reset}`);
      await runCommand('bun', ['run', 'scripts/seed.ts'], {
        DATABASE_URL: finalDbUrl,
        POSTGRES_URL: finalDbUrl,
      });
      console.log(`${c.emerald}✓ Database seeded successfully.${c.reset}`);
    } catch (dbErr: any) {
      console.error(`\n${c.rose}❌ Database push/seed failed: ${dbErr.message}${c.reset}`);
      console.log(`${c.yellow}The app will fall back to local file storage until DATABASE_URL is verified.${c.reset}`);
    }
  } else {
    console.log(`${c.yellow}No DATABASE_URL provided. Initializing local JSON fallback storage...${c.reset}`);
    const dataDir = path.dirname(STATE_FILE_PATH);
    if (!fs.existsSync(dataDir)) {
      fs.mkdirSync(dataDir, { recursive: true });
    }
    if (!fs.existsSync(STATE_FILE_PATH) && fs.existsSync(INITIAL_STATE_PATH)) {
      fs.copyFileSync(INITIAL_STATE_PATH, STATE_FILE_PATH);
      console.log(`${c.emerald}✓ Initialized data/bangkok-tracker-state.json with curated landmark spots.${c.reset}`);
    } else {
      console.log(`${c.emerald}✓ Local storage state verified at data/bangkok-tracker-state.json.${c.reset}`);
    }
  }

  // 4. Final Success Summary
  console.log(`
${c.emerald}${c.bold}========================================================================${c.reset}
${c.emerald}${c.bold}   🎉 Bangkok 50 Districts Tracker is Ready!                            ${c.reset}
${c.emerald}${c.bold}========================================================================${c.reset}

${c.bold}Configuration Overview:${c.reset}
  • ${c.slate}Storage Mode:${c.reset}      ${finalDbUrl ? `${c.emerald}PostgreSQL / Neon Database${c.reset}` : `${c.yellow}Offline Local JSON File${c.reset}`}
  • ${c.slate}Admin URL:${c.reset}         ${c.cyan}http://localhost:3000/admin${c.reset}
  • ${c.slate}Admin Password:${c.reset}    ${c.bold}${finalAdminPassword}${c.reset}
  • ${c.slate}Public Map URL:${c.reset}    ${c.cyan}http://localhost:3000${c.reset}

${c.bold}Next Steps to Start:${c.reset}
  Run ${c.emerald}${c.bold}bun dev${c.reset} (or ${c.emerald}npm run dev${c.reset}) to launch the development server.
`);
}

main().catch((err) => {
  console.error(`\n${c.rose}❌ Setup error:${c.reset}`, err);
  process.exit(1);
});
